# Generated by Django 4.2.9 on 2024-01-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db22_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaddress',
            name='street_address',
            field=models.CharField(max_length=100),
        ),
    ]
