# Generated by Django 5.0 on 2023-12-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.IntegerField()),
                ('bus_name', models.CharField(max_length=20)),
                ('bus_from', models.CharField(max_length=30)),
                ('bus_destination', models.CharField(max_length=30)),
            ],
        ),
    ]
