# Generated by Django 5.0 on 2023-12-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db22', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='passanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_name', models.CharField(max_length=20)),
                ('pass_age', models.IntegerField()),
                ('pass_from', models.CharField(max_length=20)),
                ('pass_destination', models.CharField(max_length=20)),
            ],
        ),
    ]
