# Generated by Django 5.0 on 2023-12-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empNo', models.IntegerField()),
                ('empName', models.CharField(max_length=20)),
                ('empSalary', models.IntegerField()),
                ('empAddress', models.CharField(max_length=30)),
            ],
        ),
    ]
